
spring:
  ## 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/leaf?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gaowj
    password: 123456
  application:
    name: smile-admin # 项目名称
  thymeleaf:
    cache: true # 是否启用缓存模板
    mode: HTML # 应用于模板的模板模式
    encoding: UTF-8 # 编码格式

## mybatis
mybatis:
  mapper-locations: classpath:com/smile/admin/mapper/**/*Mapper.xml
  type-aliases-package: com.smile.admin.bean.domain